// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuNNumtW3O1GPa9AUzSrsqhPgt5jPhn0Q',
    appId: '1:863248994815:web:7ff8cbd1fa8b3798cf57ca',
    messagingSenderId: '863248994815',
    projectId: 'attendance-app-4d568',
    authDomain: 'attendance-app-4d568.firebaseapp.com',
    storageBucket: 'attendance-app-4d568.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbXlNo5yrcA2RkEfkdeycVCyQ3uRdGmEs',
    appId: '1:863248994815:android:a711e75f55386a5ecf57ca',
    messagingSenderId: '863248994815',
    projectId: 'attendance-app-4d568',
    storageBucket: 'attendance-app-4d568.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAR99T0PTWiOOaVn5DXbFJYLUcQ1NdMElA',
    appId: '1:863248994815:ios:ec402a8e2660544ccf57ca',
    messagingSenderId: '863248994815',
    projectId: 'attendance-app-4d568',
    storageBucket: 'attendance-app-4d568.firebasestorage.app',
    iosBundleId: 'com.langat.attendanceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAR99T0PTWiOOaVn5DXbFJYLUcQ1NdMElA',
    appId: '1:863248994815:ios:88ca1cb71a07818bcf57ca',
    messagingSenderId: '863248994815',
    projectId: 'attendance-app-4d568',
    storageBucket: 'attendance-app-4d568.firebasestorage.app',
    iosBundleId: 'com.example.attendanceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuNNumtW3O1GPa9AUzSrsqhPgt5jPhn0Q',
    appId: '1:863248994815:web:59b9d80eb59ae879cf57ca',
    messagingSenderId: '863248994815',
    projectId: 'attendance-app-4d568',
    authDomain: 'attendance-app-4d568.firebaseapp.com',
    storageBucket: 'attendance-app-4d568.firebasestorage.app',
  );

}